Implemented C++ Hello, World!
zachflower/hello-worlds pull request #4
Opened 2024-10-15 01:24 UTC by MidnightKaze

Went ahead and added the C++ version of "Hello, World!", which is pretty similar to the C one. 

Due to some VSCode configurations the actual C++ file is generating some errors, but as far as I know it should work properly. If someone wants to confirm or give their two senses on that feel free. The part that currently pops up as an error is:

`#include <iostream>`

Again, it might just be a VSCode issue. Let me know if there's any issues!

2024-10-15 18:45 UTC, MidnightKaze commented on C++/hello.cpp
I went ahead an changed the directory to cpp and I also added that new space to the end of that line of code :D

2024-10-15 18:48 UTC, MidnightKaze commented
Since I resolved all of those conversations I'll leave another comment here too. I went ahead and changed C++ >> cpp as asked. I also added a new line character to the end of that "Hello, World!" so now the code is as such:

`std::cout << "Hello, World!" << std::endl;`

Let me know if anything else should be changed :D

2024-10-15 20:33 UTC, zachflower requested changes
@MidnightKaze one final ask! Create a `.gitignore` file in the `cpp` directory, and add `hello` to it. This will keep it so the `hello` binary can't accidentally get committed to the repository

2024-10-15 20:36 UTC, MidnightKaze commented
I gotcha. Should be in there now!

2024-10-15 20:41 UTC, zachflower requested changes
Sorry, final _final_ request

2024-10-15 20:41 UTC, zachflower commented on cpp/hello.cpp
> +    std::cout << "Hello, World!" << std::endl;
Ahh! Missed this in my review (I added tests and it caught it). Should be lowercase, no punctuation:

```suggestion
    std::cout << "hello, world" << std::endl;
```

2024-10-15 20:44 UTC, MidnightKaze commented on cpp/hello.cpp
> +    std::cout << "Hello, World!" << std::endl;
It has been done. "Hello, World!" >> "hello, world"

2024-10-24 18:22 UTC, zachflower approved these changes

2024-10-24 18:23 UTC, merged